config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :users

  
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
    has_many:users
    belongs_to:user
    validates :user_id, :title, :description, :duration, :startdate, :deadline, :author, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many:tasks
  validates :user_id, :username, :lastname, :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_id, :username, :name, :lastname, :email, :password, :password_confirmation) }
  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_id, :username, :name, :lastname, :email, :current_password) }
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]


  # GET /tasks
  # GET /tasks.json
def index
    @terminadas = Task.where(checked: true).order(deadline: :asc)
    @nterminadas = Task.where(checked: false).order(deadline: :asc)
    @vencidas = Task.where("deadline < ? and checked = ?", Date.today, false)
    @nvencidas = Task.where("deadline > ? and checked = ?", Date.today, false)
end
  
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :title, :description, :duration, :startdate, :deadline, :author, :checked)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_id, :username, :name, :lastname, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="localhost:3000">Trello</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>


    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if user_signed_in? %>
        <li class="active">
            <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
        </li>
        <%else%>
          <li class="active">
              <%= link_to "Iniciar sesion", new_user_session_path %>
          </li>
          <li class="active">
            <%= link_to "Crear cuenta", new_user_registration_path %>
          </li>
        <%end%>
      </ul>

    <ul class="left">
      <li class="co-md">
        <%= link_to "Tasks", root_path%>
      </li>

      <li class="co-md">
        <%= link_to "Users", users_path%>
      </li>
    </ul>

  </section>
</nav>
<%= yield %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :checked %><br>
    <%= f.check_box :checked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>
<div class="panel">
<h2>Unfinished Tasks</h2>

<h3>Expired</h3>
<table>
  <thead>
    <tr>
      <th>User</th>
      <!--<th>Title</th>-->
      <!--<th>Description</th>-->
      <!--<th>Duration</th>-->
      <!--<th>Startdate</th>-->
      <th>Deadline</th>
      <th>Author</th>
      <!--<th>Checked</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @vencidas.each do |task| %>
      <tr>
        <td><%= task.user_id %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.duration %></td>
        <td><%= task.startdate %></td>
        <td><%= task.deadline %></td>
        <td><%= task.author %></td>
        <td><%= task.checked %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Non Expired</h3>
<table>
  <thead>
    <tr>
      <th>User</th>
      <!--<th>Title</th>-->
      <!--<th>Description</th>-->
      <!--<th>Duration</th>-->
      <!--<th>Startdate</th>-->
      <th>Deadline</th>
      <th>Author</th>
      <!--<th>Checked</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @nvencidas.each do |task| %>
      <tr>
        <td><%= task.user_id %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.duration %></td>
        <td><%= task.startdate %></td>
        <td><%= task.deadline %></td>
        <td><%= task.author %></td>
        <td><%= task.checked %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="panel">
<h2>Finished Tasks</h2>
<table>
  <thead>
    <tr>
      <th>User</th>
      <!--<th>Title</th>-->
      <!--<th>Description</th>-->
      <!--<th>Duration</th>-->
      <!--<th>Startdate</th>-->
      <th>Deadline</th>
      <th>Author</th>
      <!--<th>Checked</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @terminadas.each do |task| %>
      <tr>
        <td><%= task.user_id %></td>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.duration %></td>
        <td><%= task.startdate %></td>
        <td><%= task.deadline %></td>
        <td><%= task.author %></td>
        <td><%= task.checked %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>


<%= link_to 'New Task', new_task_path, class:"button" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @task.startdate %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Author:</strong>
  <%= @task.author %>
</p>

<p>
  <strong>Checked:</strong>
  <%= @task.checked %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<% if user_signed_in? %>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Username</th>
      <th>Name</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= current_user.user_id %></td>
        <td><%= current_user.username %></td>
        <td><%= current_user.name %></td>
        <td><%= current_user.lastname %></td>
        <td><%= link_to 'Show', current_user %></td>
        <td><%= link_to 'Edit', edit_user_path(current_user) %></td>
        <td><%= link_to 'Destroy', current_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>
<%end%>

<br>

<!--<%= link_to 'New User', new_user_path %>-->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>